//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.22 at 05:58:42 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/soapservice/loanEligibility", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.soapservice.loaneligibility;
